// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5YbIyYRyi_k8njVYcbDBbF524MPkG2Hw',
    appId: '1:440425225323:web:a51688ea1018968ca2a52e',
    messagingSenderId: '440425225323',
    projectId: 'velo-toulouse-ab88a',
    authDomain: 'velo-toulouse-ab88a.firebaseapp.com',
    databaseURL: 'https://velo-toulouse-ab88a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-ab88a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1YRwvInA_AIGGiXqnt3T3CjdD6Q1a6U',
    appId: '1:440425225323:android:1faeda1b6cbf41eca2a52e',
    messagingSenderId: '440425225323',
    projectId: 'velo-toulouse-ab88a',
    databaseURL: 'https://velo-toulouse-ab88a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-ab88a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMs5w6-vCvZbOpG3cHE5GnkUpCsoA_sNM',
    appId: '1:440425225323:ios:8bfdc3664a272bb1a2a52e',
    messagingSenderId: '440425225323',
    projectId: 'velo-toulouse-ab88a',
    databaseURL: 'https://velo-toulouse-ab88a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-ab88a.firebasestorage.app',
    iosBundleId: 'com.example.velotoulouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMs5w6-vCvZbOpG3cHE5GnkUpCsoA_sNM',
    appId: '1:440425225323:ios:8bfdc3664a272bb1a2a52e',
    messagingSenderId: '440425225323',
    projectId: 'velo-toulouse-ab88a',
    databaseURL: 'https://velo-toulouse-ab88a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-ab88a.firebasestorage.app',
    iosBundleId: 'com.example.velotoulouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5YbIyYRyi_k8njVYcbDBbF524MPkG2Hw',
    appId: '1:440425225323:web:af7d14989a836a06a2a52e',
    messagingSenderId: '440425225323',
    projectId: 'velo-toulouse-ab88a',
    authDomain: 'velo-toulouse-ab88a.firebaseapp.com',
    databaseURL: 'https://velo-toulouse-ab88a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-ab88a.firebasestorage.app',
  );
}
